function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 0; // obj_init
	global.__objectDepths[1] = 0; // obj_player
	global.__objectDepths[2] = 0; // obj_background
	global.__objectDepths[3] = 0; // obj_cargo
	global.__objectDepths[4] = 0; // obj_wordmap_object
	global.__objectDepths[5] = 0; // obj_menu
	global.__objectDepths[6] = 0; // obj_selectgame
	global.__objectDepths[7] = 0; // obj_tutorialconfirm
	global.__objectDepths[8] = 0; // obj_deleteconfirm
	global.__objectDepths[9] = 0; // obj_arrested
	global.__objectDepths[10] = 0; // obj_robbed
	global.__objectDepths[11] = 0; // obj_destroyed
	global.__objectDepths[12] = 0; // obj_shop
	global.__objectDepths[13] = 0; // obj_garage_interaction
	global.__objectDepths[14] = 0; // obj_laser_interaction
	global.__objectDepths[15] = 0; // obj_home
	global.__objectDepths[16] = 0; // obj_depot
	global.__objectDepths[17] = 0; // obj_casino_interaction
	global.__objectDepths[18] = 0; // obj_casino_spin
	global.__objectDepths[19] = 0; // obj_thief_interaction
	global.__objectDepths[20] = 0; // obj_police_interaction
	global.__objectDepths[21] = 0; // obj_cult_interaction
	global.__objectDepths[22] = 0; // obj_alien_interaction
	global.__objectDepths[23] = 0; // obj_police_offer
	global.__objectDepths[24] = 0; // obj_thief_offer
	global.__objectDepths[25] = 0; // obj_alien_offer
	global.__objectDepths[26] = 0; // obj_cult_offer
	global.__objectDepths[27] = 0; // obj_shopdisplay
	global.__objectDepths[28] = 0; // obj_garagedisplay
	global.__objectDepths[29] = 0; // obj_laserdisplay
	global.__objectDepths[30] = 0; // obj_options
	global.__objectDepths[31] = 0; // obj_credits
	global.__objectDepths[32] = 0; // obj_asteroid
	global.__objectDepths[33] = 0; // obj_laser
	global.__objectDepths[34] = 0; // obj_explosion
	global.__objectDepths[35] = 0; // obj_dropoff
	global.__objectDepths[36] = 0; // obj_criminal
	global.__objectDepths[37] = 0; // obj_thiefboss
	global.__objectDepths[38] = 0; // obj_policeboss
	global.__objectDepths[39] = 0; // obj_cultboss
	global.__objectDepths[40] = 0; // obj_alienboss
	global.__objectDepths[41] = 0; // obj_data
	global.__objectDepths[42] = 0; // obj_name
	global.__objectDepths[43] = 0; // obj_codex
	global.__objectDepths[44] = 0; // obj_police
	global.__objectDepths[45] = 0; // obj_thief
	global.__objectDepths[46] = 0; // obj_hive
	global.__objectDepths[47] = 0; // obj_alien
	global.__objectDepths[48] = 0; // obj_alien_friendly
	global.__objectDepths[49] = 0; // obj_cultist
	global.__objectDepths[50] = 0; // obj_civillian
	global.__objectDepths[51] = 0; // obj_rich
	global.__objectDepths[52] = 0; // obj_cultistturret
	global.__objectDepths[53] = 0; // obj_money
	global.__objectDepths[54] = 0; // obj_pause
	global.__objectDepths[55] = 0; // obj_garage
	global.__objectDepths[56] = 0; // obj_lasercolor
	global.__objectDepths[57] = 0; // obj_casino
	global.__objectDepths[58] = 0; // obj_police_dropzone
	global.__objectDepths[59] = 0; // obj_thief_dropzone
	global.__objectDepths[60] = 0; // obj_alien_dropzone
	global.__objectDepths[61] = 0; // obj_cult_dropzone
	global.__objectDepths[62] = -1; // obj_abilityindicator
	global.__objectDepths[63] = 0; // obj_backdrop
	global.__objectDepths[64] = 0; // obj_turret_laser
	global.__objectDepths[65] = 0; // obj_reverse_laser
	global.__objectDepths[66] = 0; // obj_paradise_worldmap
	global.__objectDepths[67] = 0; // obj_paradise_depot
	global.__objectDepths[68] = 0; // obj_socket
	global.__objectDepths[69] = 0; // obj_paradise_transport
	global.__objectDepths[70] = 0; // obj_transport_particle
	global.__objectDepths[71] = 0; // obj_pod
	global.__objectDepths[72] = 0; // obj_rotpod
	global.__objectDepths[73] = 0; // obj_gem
	global.__objectDepths[74] = 0; // obj_intro
	global.__objectDepths[75] = 0; // obj_socket_sandbox
	global.__objectDepths[76] = 0; // obj_sandbox_interaction
	global.__objectDepths[77] = 0; // obj_sandbox_worldmap
	global.__objectDepths[78] = 0; // obj_tutorial
	global.__objectDepths[79] = 0; // obj_player_tutorial
	global.__objectDepths[80] = 0; // obj_laser_tutorial
	global.__objectDepths[81] = 0; // obj_fps_display
	global.__objectDepths[82] = 0; // obj_bar
	global.__objectDepths[83] = 0; // obj_pod_anmiation
	global.__objectDepths[84] = 0; // obj_view
	global.__objectDepths[85] = 0; // obj_itch


	global.__objectNames[0] = "obj_init";
	global.__objectNames[1] = "obj_player";
	global.__objectNames[2] = "obj_background";
	global.__objectNames[3] = "obj_cargo";
	global.__objectNames[4] = "obj_wordmap_object";
	global.__objectNames[5] = "obj_menu";
	global.__objectNames[6] = "obj_selectgame";
	global.__objectNames[7] = "obj_tutorialconfirm";
	global.__objectNames[8] = "obj_deleteconfirm";
	global.__objectNames[9] = "obj_arrested";
	global.__objectNames[10] = "obj_robbed";
	global.__objectNames[11] = "obj_destroyed";
	global.__objectNames[12] = "obj_shop";
	global.__objectNames[13] = "obj_garage_interaction";
	global.__objectNames[14] = "obj_laser_interaction";
	global.__objectNames[15] = "obj_home";
	global.__objectNames[16] = "obj_depot";
	global.__objectNames[17] = "obj_casino_interaction";
	global.__objectNames[18] = "obj_casino_spin";
	global.__objectNames[19] = "obj_thief_interaction";
	global.__objectNames[20] = "obj_police_interaction";
	global.__objectNames[21] = "obj_cult_interaction";
	global.__objectNames[22] = "obj_alien_interaction";
	global.__objectNames[23] = "obj_police_offer";
	global.__objectNames[24] = "obj_thief_offer";
	global.__objectNames[25] = "obj_alien_offer";
	global.__objectNames[26] = "obj_cult_offer";
	global.__objectNames[27] = "obj_shopdisplay";
	global.__objectNames[28] = "obj_garagedisplay";
	global.__objectNames[29] = "obj_laserdisplay";
	global.__objectNames[30] = "obj_options";
	global.__objectNames[31] = "obj_credits";
	global.__objectNames[32] = "obj_asteroid";
	global.__objectNames[33] = "obj_laser";
	global.__objectNames[34] = "obj_explosion";
	global.__objectNames[35] = "obj_dropoff";
	global.__objectNames[36] = "obj_criminal";
	global.__objectNames[37] = "obj_thiefboss";
	global.__objectNames[38] = "obj_policeboss";
	global.__objectNames[39] = "obj_cultboss";
	global.__objectNames[40] = "obj_alienboss";
	global.__objectNames[41] = "obj_data";
	global.__objectNames[42] = "obj_name";
	global.__objectNames[43] = "obj_codex";
	global.__objectNames[44] = "obj_police";
	global.__objectNames[45] = "obj_thief";
	global.__objectNames[46] = "obj_hive";
	global.__objectNames[47] = "obj_alien";
	global.__objectNames[48] = "obj_alien_friendly";
	global.__objectNames[49] = "obj_cultist";
	global.__objectNames[50] = "obj_civillian";
	global.__objectNames[51] = "obj_rich";
	global.__objectNames[52] = "obj_cultistturret";
	global.__objectNames[53] = "obj_money";
	global.__objectNames[54] = "obj_pause";
	global.__objectNames[55] = "obj_garage";
	global.__objectNames[56] = "obj_lasercolor";
	global.__objectNames[57] = "obj_casino";
	global.__objectNames[58] = "obj_police_dropzone";
	global.__objectNames[59] = "obj_thief_dropzone";
	global.__objectNames[60] = "obj_alien_dropzone";
	global.__objectNames[61] = "obj_cult_dropzone";
	global.__objectNames[62] = "obj_abilityindicator";
	global.__objectNames[63] = "obj_backdrop";
	global.__objectNames[64] = "obj_turret_laser";
	global.__objectNames[65] = "obj_reverse_laser";
	global.__objectNames[66] = "obj_paradise_worldmap";
	global.__objectNames[67] = "obj_paradise_depot";
	global.__objectNames[68] = "obj_socket";
	global.__objectNames[69] = "obj_paradise_transport";
	global.__objectNames[70] = "obj_transport_particle";
	global.__objectNames[71] = "obj_pod";
	global.__objectNames[72] = "obj_rotpod";
	global.__objectNames[73] = "obj_gem";
	global.__objectNames[74] = "obj_intro";
	global.__objectNames[75] = "obj_socket_sandbox";
	global.__objectNames[76] = "obj_sandbox_interaction";
	global.__objectNames[77] = "obj_sandbox_worldmap";
	global.__objectNames[78] = "obj_tutorial";
	global.__objectNames[79] = "obj_player_tutorial";
	global.__objectNames[80] = "obj_laser_tutorial";
	global.__objectNames[81] = "obj_fps_display";
	global.__objectNames[82] = "obj_bar";
	global.__objectNames[83] = "obj_pod_anmiation";
	global.__objectNames[84] = "obj_view";
	global.__objectNames[85] = "obj_itch";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
